/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;
import java.sql.Connection;
import java.util.Random;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
/**
 *
 * @author Hakimfrh
 */
public class LupaPassword extends javax.swing.JFrame {

    /**
     * Creates new form LupaPassword
     */
    
    String kode="";
    String noTelp="";
    String idPegawai="";
    boolean expired=false;
    boolean reSend_enable=false;
    boolean simpan_enable=false;
    
    public LupaPassword() {
        initComponents();
        readData();
        generateOTP();
        sendKode();
        lbl_noTelp.setText(String.format("+62 %s****%s",noTelp.substring(0, 3),noTelp.substring(7, noTelp.length())));
        passwd.setVisible(false);
    }
    
    private void readData(){
        try{
            String sql = "select * from pegawai where role = 'owner';";
            java.sql.Connection conn= (Connection) koneksi.configDB();
            java.sql.PreparedStatement stm=conn.prepareStatement(sql);
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()){
            idPegawai=res.getString("id_pegawai");
            noTelp=res.getString("telepon");
            if(noTelp.substring(0,1).equals("0")) noTelp=noTelp.substring(1, noTelp.length());
            }
        }catch (Exception e){
             System.out.println(e);
        }
    }
    
    private void generateOTP(){
        ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
        Random rand = new Random();
        kode = String.format("%06d",rand.nextInt(999999)); 
        expired=false;
        startFiveMinuteTimer(executorService);
    }
    
    private void sendKode(){
        ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
        Whatsapp whatsapp = new Whatsapp();
        
        String nomor = "62"+noTelp;
        String sendOTP = whatsapp.send(nomor, "Kode verifikasi 'CEK TOKO KELONTONG' adalah *"+kode +"*. Jangan bagikan kode ini pada siapapun. Kode ini digunakan untuk mengatur ulang password.");
        if (!sendOTP.equals("success")){
            JOptionPane.showMessageDialog(this, sendOTP);
            new login().setVisible(true);
            this.dispose();
        }
        startTwoMinuteTimer(executorService);
        reSend_enable=false;
        lbl_timer.setVisible(true);
        btn_kirimUlang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }
    
    private void startTwoMinuteTimer(ScheduledExecutorService executorService) {
        Runnable task = new Runnable() {
            int remainingSeconds = 2 * 60;

            public void run() {
                int minutes = remainingSeconds / 60;
                int seconds = remainingSeconds % 60;
                System.out.printf("reSend OTP : %02d:%02d\n", minutes, seconds);
                lbl_timer.setText(String.format("%02d:%02d",minutes,seconds));
                if (remainingSeconds > 0) {
                    remainingSeconds--;
                } else {
                    System.out.println("2-minute Timer expired!");
                    reSend_enable=true;
                    btn_kirimUlang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                    lbl_timer.setVisible(false);
                    executorService.shutdown();
                    // No need to shut down the executor service for this timer
                }
            }
        };

        executorService.scheduleAtFixedRate(task, 0, 1, TimeUnit.SECONDS);
    }
    
    private void startFiveMinuteTimer(ScheduledExecutorService executorService) {
        Runnable task = new Runnable() {
            int remainingSeconds = 5 * 60;

            public void run() {
                int minutes = remainingSeconds / 60;
                int seconds = remainingSeconds % 60;
                System.out.printf("expired: %02d:%02d\n", minutes, seconds);

                if (remainingSeconds > 0) {
                    remainingSeconds--;
                } else {
                    System.out.println("5-minute Timer expired!");
                    expired=true;
                    executorService.shutdown(); // Terminate the executor service
                }
            }
        };

        executorService.scheduleAtFixedRate(task, 0, 1, TimeUnit.SECONDS);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verify = new javax.swing.JPanel();
        passwd = new javax.swing.JPanel();
        txt_passwdConfirm = new javax.swing.JPasswordField();
        txt_passwd = new javax.swing.JPasswordField();
        btn_simpan = new javax.swing.JLabel();
        bg_psswd = new javax.swing.JLabel();
        txt_kodeVerifikasi = new javax.swing.JTextField();
        lbl_noTelp = new javax.swing.JLabel();
        btn_kirimUlang = new javax.swing.JLabel();
        lbl_timer = new javax.swing.JLabel();
        btn_lanjut = new javax.swing.JLabel();
        bg_verify = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verify.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_passwdConfirm.setBorder(null);
        txt_passwdConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passwdConfirmKeyReleased(evt);
            }
        });
        passwd.add(txt_passwdConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 220, 20));

        txt_passwd.setBorder(null);
        txt_passwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passwdKeyReleased(evt);
            }
        });
        passwd.add(txt_passwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 220, 20));

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Lupa password/btn_simpan_off.png"))); // NOI18N
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        passwd.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, -1, -1));

        bg_psswd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Lupa password/pn_passbaru.png"))); // NOI18N
        passwd.add(bg_psswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        verify.add(passwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 890, 360));

        txt_kodeVerifikasi.setBorder(null);
        txt_kodeVerifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodeVerifikasiActionPerformed(evt);
            }
        });
        verify.add(txt_kodeVerifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 228, 170, 20));

        lbl_noTelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_noTelp.setText("+62 857*****321");
        verify.add(lbl_noTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 180, -1));

        btn_kirimUlang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_kirimUlang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_kirimUlang.setText("Kirim ulang kode");
        btn_kirimUlang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_kirimUlang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kirimUlangMouseClicked(evt);
            }
        });
        verify.add(btn_kirimUlang, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 110, 20));

        lbl_timer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_timer.setText("0:59");
        verify.add(lbl_timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 50, 20));

        btn_lanjut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Lupa password/btn_lanjut.png"))); // NOI18N
        btn_lanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lanjutMouseClicked(evt);
            }
        });
        verify.add(btn_lanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, -1, -1));

        bg_verify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Lupa password/bg.png"))); // NOI18N
        verify.add(bg_verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kirimUlangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kirimUlangMouseClicked
        // TODO add your handling code here:
        if(reSend_enable){
            if(expired) generateOTP();
            sendKode();
        }
    }//GEN-LAST:event_btn_kirimUlangMouseClicked

    private void btn_lanjutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lanjutMouseClicked
        // TODO add your handling code here:
        if(txt_kodeVerifikasi.getText().equals(kode)) {
            passwd.setVisible(true);
        }else {
            JOptionPane.showMessageDialog(this, "Kode yang dimasukkan salah atau kadaluarsa. \nKlik tombol kirim ulang untuk mendapatkan kode baru");
            txt_kodeVerifikasi.setText("");
        }
    }//GEN-LAST:event_btn_lanjutMouseClicked

    private void txt_kodeVerifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodeVerifikasiActionPerformed
        // TODO add your handling code here:
        if(txt_kodeVerifikasi.getText().equals(kode)) {
            passwd.setVisible(true);
        }else {
            JOptionPane.showMessageDialog(this, "Kode yang dimasukkan salah atau kadaluarsa. \nKlik tombol kirim ulang untuk mendapatkan kode baru");
            txt_kodeVerifikasi.setText("");
        }
    }//GEN-LAST:event_txt_kodeVerifikasiActionPerformed

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        // TODO add your handling code here:
        if(simpan_enable){
            try{
                String sql = "UPDATE pegawai SET password = '"+txt_passwd.getText()+"' where id_pegawai = '"+idPegawai +"';";
                java.sql.Connection conn= (Connection) koneksi.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Password berhasil diubah.\nsilahkan login kembali.");
                new login().setVisible(true);
                this.dispose();
            }catch (Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }  
        }
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void txt_passwdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwdKeyReleased
        // TODO add your handling code here:
        if(txt_passwd.getText().equals(txt_passwdConfirm.getText())){
            btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Lupa password/btn_simpan_on.png")));
            simpan_enable=true;
        }else{
            btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Lupa password/btn_simpan_off.png")));
            simpan_enable=false;
        }
    }//GEN-LAST:event_txt_passwdKeyReleased

    private void txt_passwdConfirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwdConfirmKeyReleased
        // TODO add your handling code here:
        if(txt_passwd.getText().equals(txt_passwdConfirm.getText())){
            btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Lupa password/btn_simpan_on.png")));
            simpan_enable=true;
        }else{
            btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Lupa password/btn_simpan_off.png")));
            simpan_enable=false;
        }
    }//GEN-LAST:event_txt_passwdConfirmKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LupaPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_psswd;
    private javax.swing.JLabel bg_verify;
    private javax.swing.JLabel btn_kirimUlang;
    private javax.swing.JLabel btn_lanjut;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel lbl_noTelp;
    private javax.swing.JLabel lbl_timer;
    private javax.swing.JPanel passwd;
    private javax.swing.JTextField txt_kodeVerifikasi;
    private javax.swing.JPasswordField txt_passwd;
    private javax.swing.JPasswordField txt_passwdConfirm;
    private javax.swing.JPanel verify;
    // End of variables declaration//GEN-END:variables
}
