/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Hakimfrh
 */


public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    
    
    public Register() {
        initComponents();
        pn_toko.setVisible(true);
        pn_akun.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_toko = new javax.swing.JPanel();
        txt_namaToko = new javax.swing.JTextField();
        btn_lanjut = new javax.swing.JLabel();
        btn_kembali1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_alamatToko = new javax.swing.JTextArea();
        bg_toko = new javax.swing.JLabel();
        pn_akun = new javax.swing.JPanel();
        txt_nama = new javax.swing.JTextField();
        txt_telepon = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_confirmPassword = new javax.swing.JPasswordField();
        btn_kembali = new javax.swing.JLabel();
        btn_daftar = new javax.swing.JLabel();
        btn_rfid = new javax.swing.JLabel();
        lbl_rfid = new javax.swing.JLabel();
        lbl_62 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        bg_akun = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(888, 448));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_toko.setBackground(new java.awt.Color(255, 255, 255));
        pn_toko.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_namaToko.setBorder(null);
        pn_toko.add(txt_namaToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 220, 20));

        btn_lanjut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Daftar/btn_lanjut.png"))); // NOI18N
        btn_lanjut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_lanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lanjutMouseClicked(evt);
            }
        });
        pn_toko.add(btn_lanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 395, -1, -1));

        btn_kembali1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Daftar/btn_kembali.png"))); // NOI18N
        btn_kembali1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_kembali1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kembali1MouseClicked(evt);
            }
        });
        pn_toko.add(btn_kembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 395, -1, -1));

        jScrollPane2.setBorder(null);

        txt_alamatToko.setColumns(10);
        txt_alamatToko.setRows(4);
        jScrollPane2.setViewportView(txt_alamatToko);

        pn_toko.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 252, 220, 80));

        bg_toko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Daftar/bg_toko.png"))); // NOI18N
        pn_toko.add(bg_toko, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pn_toko, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 450));

        pn_akun.setBackground(new java.awt.Color(255, 255, 255));
        pn_akun.setMinimumSize(new java.awt.Dimension(888, 538));
        pn_akun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nama.setBorder(null);
        pn_akun.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 220, 20));

        txt_telepon.setBorder(null);
        pn_akun.add(txt_telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 312, 200, 20));

        txt_email.setBorder(null);
        pn_akun.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, 20));

        txt_username.setBorder(null);
        pn_akun.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 220, -1));

        txt_password.setBorder(null);
        pn_akun.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 220, 20));

        txt_confirmPassword.setBorder(null);
        pn_akun.add(txt_confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 220, 20));

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Daftar/btn_kembali.png"))); // NOI18N
        btn_kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kembaliMouseClicked(evt);
            }
        });
        pn_akun.add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 395, -1, -1));

        btn_daftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Daftar/btn_daftar.png"))); // NOI18N
        btn_daftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_daftarMouseClicked(evt);
            }
        });
        pn_akun.add(btn_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 395, -1, -1));

        btn_rfid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Daftar/btn_scanrfid.png"))); // NOI18N
        btn_rfid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_rfid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rfidMouseClicked(evt);
            }
        });
        pn_akun.add(btn_rfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        lbl_rfid.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_rfid.setText("Klik tombol untuk scan kartu");
        pn_akun.add(lbl_rfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 180, 20));

        lbl_62.setText("+62");
        pn_akun.add(lbl_62, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 312, -1, 20));

        jScrollPane1.setBorder(null);

        txt_alamat.setColumns(10);
        txt_alamat.setRows(3);
        jScrollPane1.setViewportView(txt_alamat);

        pn_akun.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 220, 80));

        bg_akun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Daftar/bg_owner.png"))); // NOI18N
        pn_akun.add(bg_akun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txt_id.setBorder(null);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        pn_akun.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 220, 0));

        getContentPane().add(pn_akun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 888, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lanjutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lanjutMouseClicked
        // TODO add your handling code here:
        if((txt_namaToko.getText().equals(""))&&(txt_alamatToko.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Silahkan isi bagian yang kosong");
        }else{
        pn_akun.setVisible(true);
        pn_toko.setVisible(false);
        }
    }//GEN-LAST:event_btn_lanjutMouseClicked

    private void btn_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMouseClicked
        // TODO add your handling code here:
        pn_toko.setVisible(true);
        pn_akun.setVisible(false);
    }//GEN-LAST:event_btn_kembaliMouseClicked

    private void btn_kembali1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembali1MouseClicked
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kembali1MouseClicked

    private void btn_daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftarMouseClicked
        // TODO add your handling code here:
        
       if((txt_id.getText().equals("")) || (txt_telepon.getText().equals("")) ||
        (txt_email.getText().equals("")) || (txt_username.getText().equals("")) ||
        (txt_password.getText().equals("")) || (txt_confirmPassword.getText().equals("")) || (txt_nama.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Silahkan isi bagian yang kosong");
            
       }else if(!txt_email.getText().contains("@")){
           JOptionPane.showMessageDialog(null, "masukkan email yang valid");
           
       }else if(!txt_password.getText().equals(txt_confirmPassword.getText())){
           JOptionPane.showMessageDialog(null, "Password tidak sama");
           
       }else{
           try{
               String sql="INSERT INTO `toko`(`nama_toko`, `nama_pemilik`, `alamat_toko`) VALUES ('"
                       +txt_namaToko.getText()+"','"
                       +txt_nama.getText()+"','"
                       +txt_alamatToko.getText()+"')";
               String sql1="INSERT INTO `pegawai`(`id_pegawai`, `nama`, `telepon`, `alamat`, `email`, `username`, `password`, `role`) VALUES ('"
                        +txt_id.getText()+"','"
                        +txt_nama.getText()+"','"
                        +txt_telepon.getText()+"','"
                        +txt_alamat.getText()+"','"
                        +txt_email.getText()+"','"
                        +txt_username.getText()+"','"
                        +txt_password.getText()+"','owner')";
                java.sql.Connection conn= (Connection) koneksi.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                java.sql.PreparedStatement pst1=conn.prepareStatement(sql1);
                pst.execute();
                pst1.execute();
                
                JOptionPane.showMessageDialog(null, "Berhasil membuat akun.\nSilahkan login kembali");
                new login().setVisible(true);
                this.dispose();
            }catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
       }
    }//GEN-LAST:event_btn_daftarMouseClicked

    private void btn_rfidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rfidMouseClicked
        // TODO add your handling code here:
        txt_id.setText("");
        txt_id.requestFocus();
        btn_rfid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Daftar/btn_scanrfid.png")));
        lbl_rfid.setText("Tempelkan karu di scanner");
    }//GEN-LAST:event_btn_rfidMouseClicked

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
        System.out.println(txt_id.getText());
        if(!txt_id.getText().equals("")){
            btn_rfid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Daftar/btn_rescan.png")));
            lbl_rfid.setText("Scan berhasil.");
        }   txt_nama.requestFocus();
    }//GEN-LAST:event_txt_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_akun;
    private javax.swing.JLabel bg_toko;
    private javax.swing.JLabel btn_daftar;
    private javax.swing.JLabel btn_kembali;
    private javax.swing.JLabel btn_kembali1;
    private javax.swing.JLabel btn_lanjut;
    private javax.swing.JLabel btn_rfid;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_62;
    private javax.swing.JLabel lbl_rfid;
    private javax.swing.JPanel pn_akun;
    private javax.swing.JPanel pn_toko;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextArea txt_alamatToko;
    private javax.swing.JPasswordField txt_confirmPassword;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_namaToko;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_telepon;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
