/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

/**
 *
 * @author Hakimfrh
 */
public class TokoKelontong extends javax.swing.JFrame {

    /**
     * Creates new form TokoKelontong
     */
    public TokoKelontong() {
        setUndecorated(true);
        initComponents();
        
        pg_Dashboard dashboard = new pg_Dashboard();
        pg_Stok stok = new pg_Stok();
        pg_Utang utang = new pg_Utang();
        pg_Transaksi transaksi = new pg_Transaksi();
        pg_Tentang tentang = new pg_Tentang();
        
        pn_dashboard.add(dashboard);
        pn_stok.add(stok);
        pn_utang.add(utang);
        pn_transaksi.add(transaksi);
        pn_tentang.add(tentang);
        
        pn_dashboard.setVisible(true);
        pn_stok.setVisible(false);
        pn_utang.setVisible(false);
        pn_transaksi.setVisible(false);
        pn_tentang.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_close = new javax.swing.JLabel();
        btn_minimize = new javax.swing.JLabel();
        btn_kasir = new javax.swing.JLabel();
        btn_Dashboard = new javax.swing.JLabel();
        btn_Stok = new javax.swing.JLabel();
        btn_Utang = new javax.swing.JLabel();
        btn_Transaksi = new javax.swing.JLabel();
        btn_Tentang = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        pn_dashboard = new javax.swing.JPanel();
        pn_stok = new javax.swing.JPanel();
        pn_utang = new javax.swing.JPanel();
        pn_transaksi = new javax.swing.JPanel();
        pn_tentang = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_exit.png"))); // NOI18N
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, -1, -1));

        btn_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_minimize.png"))); // NOI18N
        btn_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 40, -1, -1));

        btn_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_kasir.png"))); // NOI18N
        btn_kasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_kasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kasirMouseClicked(evt);
            }
        });
        getContentPane().add(btn_kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, -1, -1));

        btn_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_dashboard_on.png"))); // NOI18N
        btn_Dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DashboardMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btn_Stok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_stok_off.png"))); // NOI18N
        btn_Stok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Stok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_StokMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        btn_Utang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_utang_off.png"))); // NOI18N
        btn_Utang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Utang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_UtangMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Utang, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        btn_Transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_transaksi_off.png"))); // NOI18N
        btn_Transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TransaksiMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        btn_Tentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_tentang_off.png"))); // NOI18N
        btn_Tentang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Tentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TentangMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Tentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/bg.png"))); // NOI18N
        Background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pn_dashboard.setLayout(new javax.swing.BoxLayout(pn_dashboard, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 1366, 694));

        pn_stok.setLayout(new javax.swing.BoxLayout(pn_stok, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pn_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 1366, 694));

        pn_utang.setLayout(new javax.swing.BoxLayout(pn_utang, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pn_utang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 1366, 694));

        pn_transaksi.setLayout(new javax.swing.BoxLayout(pn_transaksi, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 1366, 694));

        pn_tentang.setLayout(new javax.swing.BoxLayout(pn_tentang, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pn_tentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 1366, 694));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMouseClicked
        // TODO add your handling code here:
        pn_dashboard.setVisible(true);
        pn_stok.setVisible(false);
        pn_utang.setVisible(false);
        pn_transaksi.setVisible(false);
        pn_tentang.setVisible(false);
        
        btn_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_dashboard_on.png")));
        btn_Stok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_stok_off.png")));
        btn_Utang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_utang_off.png")));
        btn_Transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_transaksi_off.png")));
        btn_Tentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_tentang_off.png")));
    }//GEN-LAST:event_btn_DashboardMouseClicked

    private void btn_StokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_StokMouseClicked
        // TODO add your handling code here:
        pn_dashboard.setVisible(false);
        pn_stok.setVisible(true);
        pn_utang.setVisible(false);
        pn_transaksi.setVisible(false);
        pn_tentang.setVisible(false);
        btn_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_dashboard_off.png")));
        btn_Stok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_stok_on.png")));
        btn_Utang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_utang_off.png")));
        btn_Transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_transaksi_off.png")));
        btn_Tentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_tentang_off.png")));
    }//GEN-LAST:event_btn_StokMouseClicked

    private void btn_UtangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UtangMouseClicked
        // TODO add your handling code here:
        pn_dashboard.setVisible(false);
        pn_stok.setVisible(false);
        pn_utang.setVisible(true);
        pn_transaksi.setVisible(false);
        pn_tentang.setVisible(false);
        
        btn_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_dashboard_off.png")));
        btn_Stok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_stok_off.png")));
        btn_Utang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_utang_on.png")));
        btn_Transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_transaksi_off.png")));
        btn_Tentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_tentang_off.png")));
    }//GEN-LAST:event_btn_UtangMouseClicked

    private void btn_TransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TransaksiMouseClicked
        // TODO add your handling code here:
        pn_dashboard.setVisible(false);
        pn_stok.setVisible(false);
        pn_utang.setVisible(false);
        pn_transaksi.setVisible(true);
        pn_tentang.setVisible(false);
        
        btn_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_dashboard_off.png")));
        btn_Stok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_stok_off.png")));
        btn_Utang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_utang_off.png")));
        btn_Transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_transaksi_on.png")));
        btn_Tentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_tentang_off.png")));
    }//GEN-LAST:event_btn_TransaksiMouseClicked

    private void btn_TentangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TentangMouseClicked
        // TODO add your handling code here:
        pn_dashboard.setVisible(false);
        pn_stok.setVisible(false);
        pn_utang.setVisible(false);
        pn_transaksi.setVisible(false);
        pn_tentang.setVisible(true);
        
        btn_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_dashboard_off.png")));
        btn_Stok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_stok_off.png")));
        btn_Utang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_utang_off.png")));
        btn_Transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_transaksi_off.png")));
        btn_Tentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Menu/btn_tentang_on.png")));
    }//GEN-LAST:event_btn_TentangMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        // TODO add your handling code here:
        setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void btn_kasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kasirMouseClicked
        // TODO add your handling code here:
        new Kasir().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kasirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoKelontong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoKelontong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoKelontong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoKelontong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoKelontong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel btn_Dashboard;
    private javax.swing.JLabel btn_Stok;
    private javax.swing.JLabel btn_Tentang;
    private javax.swing.JLabel btn_Transaksi;
    private javax.swing.JLabel btn_Utang;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_kasir;
    private javax.swing.JLabel btn_minimize;
    private javax.swing.JPanel pn_dashboard;
    private javax.swing.JPanel pn_stok;
    private javax.swing.JPanel pn_tentang;
    private javax.swing.JPanel pn_transaksi;
    private javax.swing.JPanel pn_utang;
    // End of variables declaration//GEN-END:variables
}
